<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Shared\Ecommerce.Shared.csproj" />
  </ItemGroup>
    

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
  </ItemGroup>
    

  <ItemGroup>
    <Reference Include="Ecommerce.Infrastructure">
      <HintPath>..\Ecommerce.Api\bin\Debug\net8.0\Ecommerce.Infrastructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
